const location = [
    'Presidencia',
    'Vicepresidencia',
    'Asamblea de accionista',
    'Junta directiva',
    'Oficina de atencion ciudadana',
    'Unidad de Auditoria interna',
    'Gerencia de planificacion y presupuesto',
    'Gerencia de gestion del despacho',
    'Consultoria juridica',
    'Gerencia de gestion comunicacional',
    'Comision de contrataciones',
    'Gerencia de talento humano',
    'Oficina de atencion ciudadana',
    'Gerencia de revision y mejora',
    'Gerencia de seguridad y prevencion',
    'Oficina de atencion ciudadana',
    'Gerencia de Administracion y finanzas',
    'Gerencia de Ingenieria y construccion',
    'Gerencia de control de perdidas y calidad de agua',
    'Gerencia de mantenimiento de agua potable y saneamiento',
    'Gerencia de operaciones sistema El Gran Falconiano',
    'Gerencia de Zonas Foraneas',
    'Gerencia de gestion popular de las agua',
    'Gerencia de comercializacion',
    'Gerencia de Transporte, Logistica y Servicios',
    'Gerencia de Tecnologia de Informacion y Comunicacion',
    'Central',
    'Sala de Servidores',
    'Deposito'
] as const
export default location 